### PR TITLE
Added delta kinematics calculations

### PR DESCRIPTION
**Pull request by armint**
Transform for rotational delta robots like FirePick Delta

### CODE REVIEW

**Comment by ambrop72** [comment]
Thanks. I've merged manually and done some improvements (5fd12e6067a74ea3a0edd1fe946b7783b168f22a). I have "tested" this on my cartesian printer and it does seem to work well.

**Comment by armint** [comment]
Cool, thanks! I will test it on my delta printer on Monday, will let you
know how it works.

Op za 1 aug. 2015 16:28 schreef Ambroz Bizjak <notifications@github.com>:

**Comment by ambrop72** [comment]
Note though, if you are running on AVR chips, do expect bad performance. On
my printer I use ArduinoDue/RADDS which should work rather well.

On Sat, Aug 1, 2015 at 4:33 PM, Armin van der Togt <notifications@github.com

**Comment by armint** [comment]
Right. I have ramps-fd and arduino due for now, and I am developing a board
based on stm32f3 or stm32f4.

Op za 1 aug. 2015 16:36 schreef Ambroz Bizjak <notifications@github.com>:

**Pull request closed without merging**
